"""AI-Ignore filter — decides which files are worth sending to the LLM.

Uses `pathspec`, the same glob matching engine that Git uses internally
for .gitignore files. This means the patterns below follow the exact
same syntax you already know from .gitignore.

KEY CONCEPT — Why filter at the source?
  Without filtering, a single `package-lock.json` (5,000+ lines) would:
    1. Waste ~10,000 tokens per API call ($$$)
    2. Generate fake "learning" entries ("Learned npm resolution")
    3. Pollute your Neo4j database with noise

  By filtering in the GitHub service (before the LLM ever sees the data),
  we keep prompts lean, responses accurate, and costs low.

KEY CONCEPT — pathspec.GitWildMatchPattern:
  This pattern class implements Git's "wildmatch" algorithm — the same
  one that processes your .gitignore rules. So you get:
    - `*.min.js`       → matches any minified JS file
    - `dist/`          → matches the entire dist directory
    - `package-lock.*` → matches lockfiles regardless of extension
"""

import pathspec

# ──────────────────────────────────────────────────────────────
# Patterns for files that have NO pedagogical value for an LLM.
# Think: "Would I learn something from reading this file?"
# If the answer is no, it goes here.
# ──────────────────────────────────────────────────────────────
AI_IGNORE_PATTERNS = """
# ── Lockfiles ──────────────────────────────────────────────
# These are auto-generated dependency manifests.
# They can be thousands of lines and contain zero learning value.
package-lock.json
pnpm-lock.yaml
yarn.lock
Cargo.lock
poetry.lock
Pipfile.lock
composer.lock
Gemfile.lock

# ── Build outputs & compiled code ──────────────────────────
# Generated by bundlers/compilers — not human-authored.
dist/
build/
.next/
out/
target/
*.min.js
*.min.css
*.css.map
*.js.map
*.bundle.js

# ── Python artifacts ───────────────────────────────────────
*.pyc
__pycache__/
*.egg-info/

# ── Media & binary files ──────────────────────────────────
# No code to analyze in images, fonts, or databases.
*.png
*.jpg
*.jpeg
*.gif
*.svg
*.ico
*.webp
*.woff
*.woff2
*.ttf
*.eot
*.mp4
*.mp3
*.pdf
*.zip
*.tar.gz

# ── Database files ─────────────────────────────────────────
*.sqlite
*.sqlite3
*.db

# ── Trivial config files ──────────────────────────────────
# These rarely contain learning-worthy code.
.prettierrc*
.eslintrc*
.editorconfig
.browserslistrc
tsconfig.json
jsconfig.json
.gitattributes

# ── Environment & secrets ─────────────────────────────────
.env
.env.*
"""

# Compile patterns ONCE at module load — O(1) per file check after this.
# from_lines() parses each non-empty, non-comment line as a glob pattern.
_spec = pathspec.PathSpec.from_lines(
    pathspec.patterns.GitWildMatchPattern,
    AI_IGNORE_PATTERNS.splitlines(),
)


def is_worth_analyzing(filename: str) -> bool:
    """
    Returns True if the file contains human-authored logic
    worth sending to the LLM for learning analysis.

    Args:
        filename: The file path from a GitHub commit (e.g. "src/main.py")

    Returns:
        True if the file should be analyzed, False if it should be skipped

    Examples:
        >>> is_worth_analyzing("src/services/github_service.py")
        True
        >>> is_worth_analyzing("package-lock.json")
        False
        >>> is_worth_analyzing("dist/bundle.min.js")
        False
    """
    return not _spec.match_file(filename)
